name: Deploy React App

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup NPM
      run: npm i && npm ci

    - name: Build
      run : npm run build

    - name: Setup Git
      run: git config user.name Ayush-Agnihotri && git config user.email 78334522+Ayush-Agnihotri@users.noreply.github.com

    - name: Work around
      run: git --work-tree build add --all

    - name: Deploy react app to github pages
      run: git commit -m "Deploy React App to GitHub Pages" && git push origin HEAD:gh-pages --force